
sources:
  - name: demo
    database: demo
    schema : demo_schema
    tables:
      - name: bike
      - name: weather
      - name : station_dimension
      - name: date_dimension
      - name : trip_fact
      - name: stg_bike
